version: "2.0"
services:
  influxdb:
    image: influxdb
    ports:
     - "8087:8086"
     - 8083/TCP
    environment:
     - INFLUXDB_USER=root
     - INFLUXDB_PASS=root
     - INFLUXDB_NAME=pistock
  grafana:
    image: grafana/grafana
    environment:    
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    links:
     - influxdb
    ports:
     - "3001:3000"
    volumes:
      - "./grafana_lib:/var/lib/grafana"
  stats:
    build: ./stat_pusher/
    depends_on: 
    - influxdb


